module.exports = {
    "title": "Reporte Semaforo",
    "labels": {
        "delivery-status": "Estatus",
        "delivery-time": "Tiempo",
        "wo-id": "No. orden",
        "cl-id": "cliente",
        "cl-corporatename": "Razón social",
        "cl-name": "Nombre(s)",
        "cl-firstsurname": "1er apellido",
        "cl-secondsurname": "2do apellido",
        "cl-type": "Tipo de Cliente",
        "zo-id": "zona",
        "zo-zone": "zona",
        "wo-orderedby": "Ordenado por",
        "wo-attention": "Atención",
        "ma-name": "Maquina",
        "wo-release": "Release",
        "wo-po": "Orden de compra",
        "wo-line": "Linea",
        "wo-linetotal": "De",
        "pr-id": "ID Producto",
        "pr-code": "Codigo de Producto",
        "pr-name": "Producto",
        "wo-qty": "Cantidad",
        "wo-packageqty": "Cantidad x paquete",
        "wo-excedentqty": "Excedente",
        "wo-foliosperformat": "Folios x formato",
        "wo-foliosseries": "Serie",
        "wo-foliosfrom": "Del",
        "wo-foliosto": "Al",
        "wo-type": "Tipo",
        "wo-commitmentdate": "Fecha compromiso",
        "wo-deliverydate": "Fecha de entrega",
        "wo-previousid": "ID anterior",
        "wo-previousdate": "Fecha anterior",
        "wo-notes": "Notas",
        "wo-price": "Precio",
        "wo-currency": "Moneda",
        "wo-email": "Enviar Correo",
        "wo-status": "Estatus ID",
        "wo-textstatus": "Estatus del proceso",
        "wo-updatedby": "Actualizado por",
        "wo-lastupdated": "Ult. Actualización",
        "wo-createdby": "Creado por",
        "wo-date": "Fec. de Creación"
    },
    "columns": [
        { "binding": "delivery_status", "type": "String", "width": 80, "wordWrap": false },
        { "binding": "delivery_time", "type": "String", "width": 120, "wordWrap": false },
        { "binding": "wo_commitmentdate", "type": "Date", "width": 140, "wordWrap": false },
        { "binding": "wo_textstatus", "type": "String", "width": 250, "wordWrap": false },
        { "binding": "wo_id", "type": "Number", "width": 100, "wordWrap": false },
        { "binding": "cl_corporatename", "type": "String", "width": 300, "wordWrap": false },
        { "binding": "zo_zone", "type": "String", "width": 300, "wordWrap": false },
        { "binding": "wo_orderedby", "type": "String", "width": 220, "wordWrap": false },
        { "binding": "pr_code", "type": "String", "width": 250, "wordWrap": false },
        { "binding": "pr_name", "type": "String", "width": 300, "wordWrap": false },
        { "binding": "wo_qty", "type": "Number", "width": 100, "wordWrap": false },
        { "binding": "ma_name", "type": "String", "width": 220, "wordWrap": false },
        { "binding": "wo_release", "type": "String", "width": 100, "wordWrap": false },
        { "binding": "wo_po", "type": "String", "width": 140, "wordWrap": false },
        { "binding": "wo_type", "type": "String", "width": 60, "wordWrap": false },
        { "binding": "wo_previousid", "type": "String", "width": 100, "wordWrap": false },
        { "binding": "wo_previousdate", "type": "Date", "width": 120, "wordWrap": false },
        { "binding": "wo_notes", "type": "String", "width": 300, "wordWrap": false },
        { "binding": "wo_updatedby", "type": "String", "width": 130, "wordWrap": false },
        { "binding": "wo_lastupdated", "type": "Date", "width": 140, "wordWrap": false },
        { "binding": "wo_createdby", "type": "String", "width": 100, "wordWrap": false },
        { "binding": "wo_date", "type": "Date", "width": 140, "wordWrap": false }
    ],
    "fields": require('../workflow/lang.es-MX').fields
}