select 
wo_id,
cl_id,
zo_id, 
wo_orderedby,
wo_attention,
rfq_id, 
wo_process,
wo_release,
wo_po,
wo_line,
wo_linetotal,
prse_id, 
wo_status, 
wo_commitmentdate,
wo_previousid,
wo_previousdate,
sh_id,
sh_date, 
wo_trackingno,
wo_shippingdate,
wo_deliverydate,
wo_invoiceno,
wo_invoicedate,
wo_notes,
wo_date
from  wo, 
jsonb_to_record(wo_jsonb) as x (
cl_id int,
zo_id int, 
wo_orderedby text,
wo_attention text,
rfq_id int, 
wo_process int,
wo_release text,
wo_po text,
wo_line int,
wo_linetotal int,
prse_id int, 
wo_status int, 
wo_commitmentdate timestamp,
wo_previousid int,
wo_previousdate timestamp,
sh_id int,
sh_date timestamp, 
wo_trackingno text,
wo_shippingdate timestamp,
wo_deliverydate timestamp,
wo_invoiceno text,
wo_invoicedate timestamp,
wo_notes text
);