module.exports = {
    "title": "Historial de la Orden",
    "labels": {
        "wo-id": "No. orden",
        "cl-id": "ID cliente",
        "cl-corporatename": "cliente",
        "zo-id": "ID zona",
        "zo-zone": "zona",
        "wo-orderedby": "Ordenado por",
        "wo-attention": "Atención",
        "pr-id": "ID Producto",
        "pr-code": "Codigo de Producto",
        "pr-name": "Producto",
        "ma-id": "ID Maquina",
        "ma-name": "Maquina",
        "wo-release": "Release",
        "wo-po": "Orden de compra",
        "wo-line": "Linea",
        "wo-linetotal": "De",    
        "wo-qty": "Cantidad",
        "wo-packageqty": "Cantidad x paq/rollo",
        "wo-foliosperformat": "Folios x formato",
        "wo-foliosseries": "Serie",
        "wo-foliosfrom": "Del",
        "wo-foliosto": "Al",
        "wo-type": "Tipo",
        "wo-commitmentdate": "Fecha compromiso",
        "wo-deliverydate": "Fecha de Entrega",
        "wo-previousid": "ID anterior",
        "wo-previousdate": "Fecha anterior",
        "wo-notes": "Notas",
        "wo-price": "Precio",
        "wo-currency": "Moneda",
        "wo-email": "Enviar Correo",
        "old-status": "Estatus Anterior",
        "new-status": "Estatus",
        "wo-createdby":"Creado por",
        "wo-updatedby":"Actualizado por",
        "wo-updated":"Actualizado",
        "wo-created": "Creado"
    },
    "columns": [
        { "binding": "wo_id", "type": "Number", "width": 100 },
        { "binding": "wo_createdby", "type": "Number", "width": 100 },
        { "binding": "wo_created", "type": "Number", "width": 150 },
        { "binding": "wo_updatedby", "type": "Number", "width": 100 },
        { "binding": "wo_updated", "type": "Number", "width": 150 },
        { "binding": "old_status", "type": "Number", "width": 150 },
        { "binding": "new_status", "type": "Number", "width": 150 }
    ]
}