module.exports = {
    "title": "Flujo de Trabajo",
    "labels": {
        "wo-id": "No. orden",
        "cl-id": "cliente",
        "cl-corporatename": "Razón social",
        "cl-firstsurname": "1er apellido",
        "cl-secondsurname": "2do apellido",
        "zo-id": "ID zona",
        "zo-zone": "Zona",
        "wo-orderedby": "Ordenado por",
        "wo-attention": "Atención",
        "ma-id": "Maquina",
        "wo-release": "Release",
        "wo-po": "Orden de compra",
        "wo-line": "Linea",
        "wo-linetotal": "De",
        "pr-id": "ID Producto",
        "pr-code":"Codigo de Producto",
        "pr-process":"Proceso",
        "pr-name": "Producto",
        "ma-name": "Maquina",
        "pr-material": "Material",
        "inkfront": "No. Tintas F.",
        "inksfront": "Tintas F.",
        "inkback": "No. Tintas R.",
        "inksback": "Tintas R.",
        "wo-qty": "Cantidad",
        "wo-packageqty": "Cantidad x paquete",
        "wo-boxqty": "Cantidad x caja",
        "wo-excedentqty": "Excedente",
        "wo-foliosperformat": "Folios x formato",
        "wo-foliosseries": "Serie",
        "wo-foliosfrom": "Del",
        "wo-foliosto": "Al",
        "wo-type": "Tipo",
        "wo-commitmentdate": "Fecha compromiso",
        "wo-previousid": "ID anterior",
        "wo-previousdate": "Fecha anterior",
        "wo-notes": "Notas",
        "wo-price": "Precio",
        "wo-currency": "Moneda",
        "wo-email": "Enviar Correo",
        "wo-status": "Estatus",
        "wo-updatedby": "Actualizado por",
        "wo-updated": "Fecha de Actualización",
        "wo-createdby": "Creado por",
        "wo-date": "Fecha"
    },
    "columns": [
        "wo_type",
        "pr_process",
        "wo_id",
        "wo_commitmentdate",
        "cl_id",
        "cl_corporatename",
        "zo_zone",
        "pr_code",
        "pr_name",
        "ma_name",
        "pr_material",
        "inkfront",
        "inksfront",
        "inkback",
        "inksback",
        "wo_po",
        "wo_qty",
        "wo_packageqty",
        "wo_boxqty",
        "wo_foliosperformat",
        "wo_foliosseries",
        "wo_foliosfrom",
        "wo_foliosto",
        "wo_notes",
        "wo_previousid",
        "wo_previousdate",
        "wo_status",
        "wo_updatedby",
        "wo_updated",
        "wo_createdby",
        "wo_date"
    ],
    "fields": {
        wo_statusoptions: [
            { "label": "Activo", "value": 0, "desc": "Orden Activa", "us_group": "sales", "wo_prevstatus": [] },
            { "label": "En espera de material", "value": 1, "desc": "No hay material en el almacén", "us_group": "warehouse", "wo_prevstatus": [0, 4, 6, 9, 16] },
            { "label": "Material disponible", "value": 2, "desc": "Hay material en el almacén pero aun no se ha iniciado el trabajo", "us_group": "production", "wo_prevstatus": [1] },
            { "label": "En producción", "value": 3, "desc": "En producción", "us_group": "production", "wo_prevstatus": [2,4] },
            { "label": "Detenido en Producción", "value": 4, "desc": "La orden se detuvo en producción", "us_group": "production", "wo_prevstatus": [3] },
            { "label": "Acabados", "value": 5, "desc": "Procesando Acabados", "us_group": "finishing", "wo_prevstatus": [3, 6] },
            { "label": "Detenido en Acabados", "value": 6, "desc": "La orden se detuvo en producción", "us_group": "finishing", "wo_prevstatus": [5] },
            { "label": "Terminado", "value": 7, "desc": "Terminado en producción", "us_group": "quality_assurance", "wo_prevstatus": [5] },
            { "label": "Departamento de calidad", "value": 8, "desc": "Inspeccion de calidad en proceso", "us_group": "quality_assurance", "wo_prevstatus": [1,7] },
            { "label": "Rechazado por calidad", "value": 9, "desc": "Rechazado por calidad", "us_group": "warehouse", "wo_prevstatus": [8] },
            { "label": "Aprobado por calidad", "value": 10, "desc": "Aprobado por calidad", "us_group": "packaging", "wo_prevstatus": [8] },
            { "label": "Empaque", "value": 11, "desc": "En proceso de empaque", "us_group": "packaging", "wo_prevstatus": [10] },
            { "label": "Inspección Final", "value": 12, "desc": "Listo para embarque", "us_group": "quality_assurance", "wo_prevstatus": [11] },
            { "label": "Facturación/Lista de Embarque", "value": 13, "desc": "Facturado", "us_group": "warehouse", "wo_prevstatus": [12] },
            { "label": "Enviado", "value": 14, "desc": "Los articulos fueron enviados", "us_group": "warehouse", "wo_prevstatus": [13] },
            { "label": "No se pudo entregar", "value": 15, "desc": "El producto no se pudo entregar", "us_group": "warehouse", "wo_prevstatus": [14] },
            { "label": "Rechazado por el cliente", "value": 16, "desc": "El producto fue rechazado por el cliente", "us_group": "warehouse", "wo_prevstatus": [14, 15] },
            { "label": "Entregado", "value": 17, "desc": "El producto se entrego al cliente con éxito", "us_group": "warehouse", "wo_prevstatus": [14, 15] },
            { "label": "Cancelada", "value": 18, "desc": "La orden de trabajo fue cancelada", "us_group": "admin", "wo_prevstatus": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,17,18] }
        ]
    }
}