module.exports = {
    "title": "direcciones de envio",
    "labels": {
        "zo-id": "id zona",
        "cl-id": "id cliente",
        "zo-type": "tipo",
        "zo-zone": "zona",
        "zo-corporatename": "razón social",
        "zo-rfc": "rfc",
        "zo-immex": "immex",
        "zo-name": "nombre",
        "zo-fatherslastname": "1er apellido",
        "zo-motherslastname": "2do apellido",
        "zo-street": "calle",
        "zo-streetnumber": "numero exterior",
        "zo-suitenumber": "numero interior",
        "zo-neighborhood": "colonia",
        "zo-addressreference": "referencia",
        "zo-country": "país",
        "zo-state": "estado",
        "zo-city": "ciudad",
        "zo-county": "municipio",
        "zo-zipcode": "codigo postal",
        "zo-email": "correo electrónico",
        "zo-phone": "teléfono",
        "zo-phoneextension": "Ext.",
        "zo-mobile": "móvil",
        "zo-status": "estatus",
        "zo-date": "fecha",

    },
    "columns": [
        "zo_id",
        "cl_id",
        "zo_zone",
        "zo_corporatename",
        "zo_rfc",
        "zo_immex",
        "zo_name",
        "zo_fatherslastname",
        "zo_motherslastname",
        "zo_street",
        "zo_streetnumber",
        "zo_suitenumber",
        "zo_neighborhood",
        "zo_addressreference",
        "zo_zipcode",
        "zo_email",
        "zo_phone",
        "zo_phoneextension",
        "zo_mobile",
        "zo_status",
        "zo_type",
        "zo_date",
    ],
    "fields": {
        zo_statusoptions: [
            { "label": "Activo", "value": "A" },
            { "label": "Inactivo", "value": "I" }
        ],
        zo_typeoptions: [
            { "label": "Fisica", "value": "natural" },
            { "label": "Moral", "value": "legal" }
        ]
    }
}