module.exports = {
    "title": "Ordenes de trabajo",
    "labels": {
        "cl-id": "id cliente",
        "zo-id": "id zona",
        "wo-orderedby": "ordenado por",
        "wo-attention": "atención",
        "ma-id": "Maquina",
        "wo-release": "release",
        "wo-po": "orden de compra",
        "wo-line": "linea",
        "wo-linetotal": "total lineas",
        "pr-id": "id producto",
        "pr-partno": "No. de parte",
        "pr-code": "Codigo",
        "pr-Name": "Nombre",
        "wo-qty": "Cantidad",
        "wo-excedentqty": "Excedente",
        "wo-foliosperformat": "Folios por formato",
        "wo-foliosseries": "Serie",
        "wo-foliosfrom": "Del",
        "wo-foliosto": "Al",
        "wo-type":"Tipo",
        "wo-id": "no. orden",
        "wo-date": "fecha",
        "wo-commitmentdate": "fecha compromiso",
        "wo-previousid": "id anterior",
        "wo-previousdate": "fecha anterior",
        "wo-notes": "notas",
        "wo-price": "Precio",
        "wo-currency": "Moneda",
        "wo-email": "Enviar Correo",
        "wo-status": "estatus"        
    },
    "columns": [
        "cl-id",
        "zo-id",
        "wo-orderedby",
        "wo-attention", 
        "ma-id", 
        "wo-release",
        "wo-po", 
        "wo-line",
        "wo-linetotal",
        "pr-id", 
        "pr-partno", 
        "pr-code", 
        "pr-Name", 
        "wo-qty", 
        "wo-excedentqty", 
        "wo-foliosperformat", 
        "wo-foliosseries", 
        "wo-foliosfrom", 
        "wo-foliosto", 
        "wo-type",
        "wo-id", 
        "wo-date", 
        "wo-commitmentdate", 
        "wo-previousid", 
        "wo-previousdate", 
        "wo-notes", 
        "wo-price", 
        "wo-currency", 
        "wo-email", 
        "wo-status" 
    ]
}