module.exports = {
    "title": "Ordenes de Trabajo",
    "labels": {
        "wo-id": "No. orden",
        "cl-id": "ID cliente",
        "cl-corporatename": "cliente",
        "zo-id": "ID zona",
        "zo-zone": "zona",
        "wo-orderedby": "Ordenado por",
        "wo-attention": "Atención",
        "pr-id": "ID Producto",
        "pr-code": "Codigo de Producto",
        "pr-name": "Producto",
        "ma-id": "ID Maquina",
        "ma-name": "Maquina",
        "wo-release": "Release",
        "wo-po": "Orden de compra",
        "wo-line": "Linea",
        "wo-linetotal": "De",    
        "wo-qty": "Cantidad",
        "wo-packageqty": "Cantidad x paq/rollo",
        "wo-foliosperformat": "Folios x formato",
        "wo-foliosseries": "Serie",
        "wo-foliosfrom": "Del",
        "wo-foliosto": "Al",
        "wo-type": "Tipo",
        "wo-commitmentdate": "Fecha compromiso",
        "wo-deliverydate": "Fecha de Entrega",
        "wo-previousid": "ID anterior",
        "wo-previousdate": "Fecha anterior",
        "wo-notes": "Notas",
        "wo-price": "Precio",
        "wo-currency": "Moneda",
        "wo-email": "Enviar Correo",
        "wo-status": "Estatus",
        "wo-createdby":"Creado por",
        "wo-updatedby":"Actualizado por",
        "wo-updatedate":"Fecha de Actualizacion",
        "wo-date": "Fecha"
    },
    "columns": [
        "wo_id",
        "cl_corporatename",
        "zo_zone",
        "pr_code",
        "pr_name",
        "ma_name",
        "wo_orderedby",
        "wo_attention",
        "wo_release",
        "wo_po",
        "wo_line",
        "wo_linetotal",
        "wo_qty",
        "wo_packageqty",
        "wo_foliosperformat",
        "wo_foliosseries",
        "wo_foliosfrom",
        "wo_foliosto",
        "wo_type",
        "wo_commitmentdate",
        "wo_deliverydate",
        "wo_previousid",
        "wo_previousdate",
        "wo_notes",
        "wo_price",
        "wo_currency",
        "wo_email",
        "wo_status",
        "wo_createdby",
        "wo_updatedby",
        "wo_updated",
        "wo_date"
    ]
}