select 
    *
from  wo, 
jsonb_to_record(wo_jsonb, true) as x (
        cl_id int,
        zo_id int,
        wo_orderedby text,
        wo_attention text, 
        ma_id int, 
        wo_release text,
        wo_po text, 
        wo_line int,
        wo_linetotal int,
        pr_id int, 
        pr_partno text, 
        pr_code text, 
        pr_name text, 
        wo_qty int, 
        wo_excedentqty int, 
        wo_foliosperformat int, 
        wo_foliosseries text, 
        wo_foliosfrom int, 
        wo_foliosto int, 
        wo_type text,
        wo_id int, 
        wo_date timestamp, 
        wo_commitmentdate timestamp, 
        wo_previousid int, 
        wo_previousdate int, 
        wo_notes text, 
        wo_price text, 
        wo_currency text, 
        wo_email text, 
        wo_status text
)
where wo_jsonb->>'cl_id' = $1;